In [24]:
import pandas as pd

nhanes = pd.read_csv("nhanes.csv")

In [25]:
nhanes

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BPXOSY1,BPXODI1,LBXTC
0,132141.0,12.0,2.0,2.0,56.0,4.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,115.0,70.0,205.0
1,136977.0,12.0,2.0,1.0,29.0,3.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,2.0,3.0,2.0,2.0,125.0,71.0,193.0
2,134280.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,111.0,69.0,87.0
3,132522.0,12.0,2.0,2.0,64.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,113.0,90.0,215.0
4,138725.0,12.0,2.0,2.0,28.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,114.0,69.0,215.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,138255.0,12.0,2.0,2.0,65.0,5.0,2.0,1.0,NaN,4.0,...,NaN,8.0,NaN,2.0,1.0,2.0,1.0,99.0,62.0,144.0
5699,134584.0,12.0,2.0,1.0,56.0,1.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,3.0,2.0,3.0,137.0,102.0,235.0
5700,133659.0,12.0,2.0,2.0,80.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,9.0,2.0,NaN,NaN,NaN,126.0,65.0,156.0
5701,131701.0,12.0,2.0,2.0,46.0,3.0,2.0,1.0,NaN,3.0,...,NaN,NaN,NaN,1.0,2.0,1.0,NaN,121.0,76.0,291.0
5702,136760.0,12.0,2.0,2.0,73.0,5.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,3.0,2.0,4.0,122.0,71.0,271.0

In [26]:
for column in nhanes.columns:
    print(column, nhanes[column].unique(), "\n", nhanes[column].describe(), "\n")

SEQN [132141. 136977. 134280. ... 133659. 131701. 136760.]
 count      5703.000000
mean     136349.344906
std        3434.441227
min      130379.000000
25%      133347.000000
50%      136383.000000
75%      139318.000000
max      142310.000000
Name: SEQN, dtype: float64

SDDSRVYR [12.]
 count    5703.0
mean       12.0
std         0.0
min        12.0
25%        12.0
50%        12.0
75%        12.0
max        12.0
Name: SDDSRVYR, dtype: float64

RIDSTATR [2.]
 count    5703.0
mean        2.0
std         0.0
min         2.0
25%         2.0
50%         2.0
75%         2.0
max         2.0
Name: RIDSTATR, dtype: float64

RIAGENDR [2. 1.]
 count    5703.000000
mean        1.546204
std         0.497904
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         2.000000
Name: RIAGENDR, dtype: float64

RIDAGEYR [56. 29. 25. 64. 28. 52. 34. 65. 44. 33. 69. 35. 63. 31. 80. 27. 58. 37.
 72. 20. 68. 39. 49. 59. 71. 73. 54. 75. 18. 70. 61. 36. 42. 60. 22. 30.
 23. 62. 45. 32. 55. 46. 66. 78. 53. 67. 77. 57. 19. 48. 47. 51. 74. 43.
 50. 24. 40. 76. 41. 38. 26. 21. 79.]
 count    5703.000000
mean       52.334911
std        18.352717
min        18.000000
25%        37.000000
50%        56.000000
75%        68.000000
max        80.000000
Name: RIDAGEYR, dtype: float64

RIDRETH1 [4. 3. 1. 2. 5.]
 count    5703.000000
mean        3.123619
std         0.984967
min         1.000000
25%         3.000000
50%         3.000000
75%         3.000000
max         5.000000
Name: RIDRETH1, dtype: float64

DMQMILIZ [2. 1.]
 count    5703.000000
mean        1.912502
std         0.282588
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         2.000000
Name: DMQMILIZ, dtype: float64

DMDBORN4 [1. 2.]
 count    5703.000000
mean        1.199895
std         0.399956
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: DMDBORN4, dtype: float64

DMDYRUSR [nan  2.  6.  4.  3.  5.  1. 99. 77.]
 count    1140.000000
mean        6.900000
std        13.346618
min         1.000000
25%         4.000000
50%         6.000000
75%         6.000000
max        99.000000
Name: DMDYRUSR, dtype: float64

DMDEDUC2 [ 5.  4.  3.  2. nan  1.  9.]
 count    5449.000000
mean        3.840154
std         1.137708
min         1.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         9.000000
Name: DMDEDUC2, dtype: float64

DMDMARTZ [ 2.  3.  1. nan 99. 77.]
 count    5448.000000
mean        1.694934
std         1.848045
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        99.000000
Name: DMDMARTZ, dtype: float64

DMDHHSIZ [1. 4. 2. 5. 3. 6. 7.]
 count    5703.000000
mean        2.624408
std         1.487554
min         1.000000
25%         2.000000
50%         2.000000
75%         4.000000
max         7.000000
Name: DMDHHSIZ, dtype: float64

WTINT2YR [23268.517225 34123.883392 41707.768081 ... 22242.56237  21413.999631
 12563.740681]
 count      5703.000000
mean      30788.284158
std       21286.852544
min        4584.463196
25%       16043.897765
50%       24698.020587
75%       38028.369826
max      170968.343177
Name: WTINT2YR, dtype: float64

WTMEC2YR [27202.5521   49979.038191 47698.256405 ... 32535.602765 32386.80983
 17067.067586]
 count      5703.000000
mean      40013.039157
std       28993.983123
min        4581.595095
25%       20037.286657
50%       31554.405988
75%       49791.522844
max      227108.296958
Name: WTMEC2YR, dtype: float64

ALQ111 [ 1. nan  2.  9.]
 count    4929.000000
mean        1.107730
std         0.376295
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         9.000000
Name: ALQ111, dtype: float64

ALQ121 [9.00000000e+00 7.00000000e+00 6.00000000e+00 5.39760535e-79
 2.00000000e+00 4.00000000e+00 3.00000000e+00 5.00000000e+00
            nan 1.00000000e+00 1.00000000e+01 8.00000000e+00
 7.70000000e+01 9.90000000e+01]
 count    4.429000e+03
mean     5.000226e+00
std      3.936861e+00
min      5.397605e-79
25%      2.000000e+00
50%      5.000000e+00
75%      8.000000e+00
max      9.900000e+01
Name: ALQ121, dtype: float64

ALQ130 [  2.   3.  nan   4.   1.  12.   5.   6.  15.  10.   8.  14.   7.   9.
  13. 999. 777.  11.]
 count    3657.000000
mean        5.180476
std        48.900227
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max       999.000000
Name: ALQ130, dtype: float64

ALQ151 [ 2.  1. nan  9.]
 count    4409.000000
mean        1.821048
std         0.444723
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         9.000000
Name: ALQ151, dtype: float64

ALQ170 [           nan 1.00000000e+00 5.39760535e-79 8.00000000e+00
 2.00000000e+00 4.00000000e+00 5.00000000e+00 3.00000000e+00
 3.00000000e+01 2.00000000e+01 1.00000000e+01 9.99000000e+02
 6.00000000e+00 1.50000000e+01 7.00000000e+00 1.40000000e+01
 1.20000000e+01 7.77000000e+02 1.80000000e+01 9.00000000e+00
 1.70000000e+01 1.30000000e+01]
 count    2.113000e+03
mean     4.159962e+00
std      4.258466e+01
min      5.397605e-79
25%      5.397605e-79
50%      1.000000e+00
75%      2.000000e+00
max      9.990000e+02
Name: ALQ170, dtype: float64

HIQ011 [1. 2. 9. 7.]
 count    5703.000000
mean        1.101526
std         0.468626
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         9.000000
Name: HIQ011, dtype: float64

HIQ032A [ 1. nan 99. 77.]
 count    3037.000000
mean        2.770826
std        12.950200
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max        99.000000
Name: HIQ032A, dtype: float64

HIQ032B [nan  2.]
 count    1977.0
mean        2.0
std         0.0
min         2.0
25%         2.0
50%         2.0
75%         2.0
max         2.0
Name: HIQ032B, dtype: float64

HIQ032D [nan  4.]
 count    841.0
mean       4.0
std        0.0
min        4.0
25%        4.0
50%        4.0
75%        4.0
max        4.0
Name: HIQ032D, dtype: float64

HIQ032F [nan  6.]
 count    238.0
mean       6.0
std        0.0
min        6.0
25%        6.0
50%        6.0
75%        6.0
max        6.0
Name: HIQ032F, dtype: float64

HIQ032H [nan  8.]
 count    434.0
mean       8.0
std        0.0
min        8.0
25%        8.0
50%        8.0
75%        8.0
max        8.0
Name: HIQ032H, dtype: float64

HIQ032I [nan  9.]
 count    225.0
mean       9.0
std        0.0
min        9.0
25%        9.0
50%        9.0
75%        9.0
max        9.0
Name: HIQ032I, dtype: float64

HIQ210 [ 2.  1. nan  9.  7.]
 count    5218.000000
mean        1.966079
std         0.375346
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         9.000000
Name: HIQ210, dtype: float64

INDFMMPC [ 3. nan  2.  1.  9.  7.]
 count    5229.000000
mean        2.494358
std         1.246655
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         9.000000
Name: INDFMMPC, dtype: float64

INQ300 [ 1.  2. nan  9.  7.]
 count    5230.000000
mean        1.727533
std         1.269765
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         9.000000
Name: INQ300, dtype: float64

IND310 [nan  2.  1.  3.  5.  4. 99. 77.]
 count    2579.000000
mean        3.367584
std        12.382223
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        99.000000
Name: IND310, dtype: float64

BPXOSY1 [115. 125. 111. 113. 114. 138. 100. 142. 109. 130. 121. 131.  95. 155.
 110. 132.  nan 126.  99. 122. 107. 141. 112. 162.  98. 106. 157.  96.
  94. 133. 118. 103. 104. 105. 123. 119.  84. 117. 140.  80. 101. 127.
 136. 124.  89. 134. 120. 152. 102. 146. 156. 176. 128. 153. 116. 139.
 151. 148. 129. 147. 161. 195. 180.  97.  92. 179. 135. 232. 154. 108.
 163. 181. 137. 159. 150. 143.  85. 145. 182. 194.  87. 170. 149. 168.
  86.  83. 158. 216. 167. 144.  82.  91. 166. 172.  93. 189. 187. 175.
  77. 171. 201. 178. 174. 185. 203. 164. 209. 160. 196. 202. 165.  90.
 192. 193. 183. 190.  81.  78. 173.  88. 224. 177. 169. 197. 188.  75.
 199. 191. 211. 184. 225. 210. 200.  73.]
 count    5510.000000
mean      122.599274
std        18.512221
min        73.000000
25%       110.000000
50%       120.000000
75%       133.000000
max       232.000000
Name: BPXOSY1, dtype: float64

BPXODI1 [ 70.  71.  69.  90.  82.  75.  83.  73.  86.  74.  76.  60.  64.  89.
  80.  65.  66.  nan  57.  78.  58.  88.  72.  59.  55.  96.  87.  79.
  45.  68.  67.  61.  56.  63.  93.  62.  85.  81.  77. 105. 101.  48.
 106.  84.  99. 100.  52.  91.  97. 111.  98.  41.  95. 116. 115.  54.
  94.  92. 113.  53. 103.  46. 102.  44.  51.  49. 108.  40. 114. 112.
 138. 117. 128. 110.  50. 104.  39. 131. 109.  37.  42. 130. 107.  38.
 125. 120. 142.  36.  47.]
 count    5510.000000
mean       74.945554
std        11.428117
min        36.000000
25%        67.000000
50%        74.000000
75%        82.000000
max       142.000000
Name: BPXODI1, dtype: float64

LBXTC [205. 193.  87. 215.  nan 190. 194. 207. 165. 219. 185. 140. 144. 226.
 195. 113. 125. 147. 184. 172. 146. 179. 222. 249. 178. 141. 122. 191.
 230. 224. 132. 209. 168. 199. 247. 228. 158. 162. 129. 134. 248. 188.
 319. 217. 181. 331. 270. 237.  93. 210. 157. 198. 312. 206. 208. 128.
 166. 160. 148.  62. 227. 174. 293. 156. 231. 180. 204. 130. 142. 159.
 167. 154. 300. 264. 131. 197. 124. 161. 153. 221. 189. 246. 192. 220.
 138. 243. 150. 202. 296. 265. 273. 211. 145. 177. 135. 216. 171. 176.
 151. 196. 214. 262. 234. 152. 119. 241. 305. 163. 290. 173. 139. 164.
 170. 187. 261. 175. 242. 303. 250. 213. 169. 200. 251. 238. 232. 235.
 252. 133. 126. 225. 183. 257.  98. 203. 143. 223. 186. 294. 114. 182.
 116. 201. 212. 155. 364. 149. 254. 115. 245. 268. 286. 136. 244. 118.
 101. 279. 127. 107. 267. 233. 263. 284. 239. 240. 255. 108. 123. 137.
 218. 121. 344. 105. 253. 236. 301. 120. 269. 106. 285. 321. 229. 256.
 117.  94. 112. 287. 304. 258. 260. 393. 274.  91. 109. 275.  99. 271.
  74. 280. 259. 438.  95.  89. 345.  81.  97. 362. 276. 398. 316. 111.
 272. 110. 102. 376. 349. 334.  90.  84. 326. 313. 104. 103. 278. 266.
 328. 314.  80. 282. 289. 308. 281. 306. 302. 335. 100. 292. 291. 310.
 391.  86. 298.  88. 277. 318. 320.  63. 311. 333. 315. 361. 327. 342.
 389. 283. 341. 297. 317. 338.]
 count    5145.000000
mean      186.921866
std        42.602522
min        62.000000
25%       157.000000
50%       184.000000
75%       213.000000
max       438.000000
Name: LBXTC, dtype: float64

In [27]:
nhanes.info()

<class 'pandas.DataFrame'>
RangeIndex: 5703 entries, 0 to 5702
Data columns (total 33 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      5703 non-null   float64
 1   SDDSRVYR  5703 non-null   float64
 2   RIDSTATR  5703 non-null   float64
 3   RIAGENDR  5703 non-null   float64
 4   RIDAGEYR  5703 non-null   float64
 5   RIDRETH1  5703 non-null   float64
 6   DMQMILIZ  5703 non-null   float64
 7   DMDBORN4  5703 non-null   float64
 8   DMDYRUSR  1140 non-null   float64
 9   DMDEDUC2  5449 non-null   float64
 10  DMDMARTZ  5448 non-null   float64
 11  DMDHHSIZ  5703 non-null   float64
 12  WTINT2YR  5703 non-null   float64
 13  WTMEC2YR  5703 non-null   float64
 14  ALQ111    4929 non-null   float64
 15  ALQ121    4429 non-null   float64
 16  ALQ130    3657 non-null   float64
 17  ALQ151    4409 non-null   float64
 18  ALQ170    2113 non-null   float64
 19  HIQ011    5703 non-null   float64
 20  HIQ032A   3037 non-null   float64
 21  HIQ032B   1977 non-null   float64
 22  HIQ032D   841 non-null    float64
 23  HIQ032F   238 non-null    float64
 24  HIQ032H   434 non-null    float64
 25  HIQ032I   225 non-null    float64
 26  HIQ210    5218 non-null   float64
 27  INDFMMPC  5229 non-null   float64
 28  INQ300    5230 non-null   float64
 29  IND310    2579 non-null   float64
 30  BPXOSY1   5510 non-null   float64
 31  BPXODI1   5510 non-null   float64
 32  LBXTC     5145 non-null   float64
dtypes: float64(33)
memory usage: 1.4 MB

In [28]:
def bpSYmap(bp):
    if bp >= 120:
        return 1
    else:
        return 0
def bpDImap(bp):
    if bp >= 80:
        return 1
    else:
        return 0 

def normmap(bp):
    if bp == 0:
        return "normal"
    else:
        return "abnormal"

def cholmap(chol):
    if chol < 200:
        return "normal"
    elif chol <= 239:
        return "borderline"
    else:
        return "high"

nhanes["BP"] = nhanes["BPXOSY1"].map(bpSYmap) + nhanes["BPXODI1"].map(bpDImap)
nhanes["BP"] = nhanes["BP"].map(normmap)


nhanes["CHOL"] = nhanes["LBXTC"].map(cholmap)

In [29]:
nhanes.drop(labels=["BPXOSY1", "BPXODI1", "LBXTC"], axis=1, inplace=True)

In [30]:
nhanes

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
0,132141.0,12.0,2.0,2.0,56.0,4.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline
1,136977.0,12.0,2.0,1.0,29.0,3.0,2.0,2.0,2.0,5.0,...,4.0,NaN,NaN,NaN,2.0,3.0,2.0,2.0,abnormal,normal
2,134280.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,normal
3,132522.0,12.0,2.0,2.0,64.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,abnormal,borderline
4,138725.0,12.0,2.0,2.0,28.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,138255.0,12.0,2.0,2.0,65.0,5.0,2.0,1.0,NaN,4.0,...,NaN,NaN,8.0,NaN,2.0,1.0,2.0,1.0,normal,normal
5699,134584.0,12.0,2.0,1.0,56.0,1.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,abnormal,borderline
5700,133659.0,12.0,2.0,2.0,80.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,9.0,2.0,NaN,NaN,NaN,abnormal,normal
5701,131701.0,12.0,2.0,2.0,46.0,3.0,2.0,1.0,NaN,3.0,...,NaN,NaN,NaN,NaN,1.0,2.0,1.0,NaN,abnormal,high
5702,136760.0,12.0,2.0,2.0,73.0,5.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,4.0,abnormal,high

In [31]:
#why ae we doing processing directly on the dataset if we're going to need to make a pipeline for it anyway? Wouldn't it be more reliable to just use the pipeline both times?

In [32]:
bp_Stanford = nhanes
chol_Stanford = nhanes

In [33]:
from sklearn.model_selection import train_test_split

bp_training_Stanford, bp_test_Stanford = train_test_split(bp_Stanford, train_size=.8, random_state=42, stratify=bp_Stanford["BP"])

chol_training_Stanford, chol_test_Stanford = train_test_split(bp_Stanford, train_size=.8, random_state=42, stratify=chol_Stanford["CHOL"])

In [34]:
bp_training_Stanford

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
3783,140293.0,12.0,2.0,2.0,63.0,1.0,2.0,1.0,NaN,3.0,...,NaN,NaN,NaN,NaN,1.0,3.0,2.0,3.0,abnormal,high
2412,136499.0,12.0,2.0,2.0,38.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,normal,normal
3834,141952.0,12.0,2.0,2.0,63.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,8.0,NaN,2.0,3.0,1.0,NaN,normal,borderline
2345,134955.0,12.0,2.0,1.0,65.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,normal
3658,135090.0,12.0,2.0,2.0,70.0,5.0,2.0,2.0,6.0,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,abnormal,borderline
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2998,130580.0,12.0,2.0,1.0,51.0,2.0,2.0,2.0,1.0,2.0,...,4.0,NaN,NaN,NaN,2.0,2.0,2.0,1.0,abnormal,borderline
900,136079.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,4.0,...,NaN,6.0,NaN,NaN,2.0,3.0,1.0,NaN,normal,normal
3108,131930.0,12.0,2.0,2.0,26.0,1.0,2.0,2.0,6.0,4.0,...,NaN,NaN,8.0,NaN,2.0,1.0,2.0,1.0,normal,normal
2876,138262.0,12.0,2.0,1.0,19.0,1.0,2.0,1.0,NaN,NaN,...,4.0,NaN,NaN,NaN,2.0,1.0,2.0,1.0,normal,normal
5582,135484.0,12.0,2.0,2.0,37.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,borderline

In [35]:
chol_training_Stanford

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
3956,132383.0,12.0,2.0,2.0,73.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,normal,borderline
2119,135622.0,12.0,2.0,1.0,65.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,normal,borderline
227,137375.0,12.0,2.0,2.0,60.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,abnormal,borderline
519,140925.0,12.0,2.0,2.0,54.0,4.0,2.0,1.0,NaN,4.0,...,4.0,NaN,NaN,9.0,2.0,1.0,2.0,1.0,abnormal,normal
2090,138698.0,12.0,2.0,2.0,66.0,2.0,2.0,2.0,4.0,4.0,...,NaN,NaN,NaN,9.0,2.0,2.0,2.0,1.0,normal,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,139655.0,12.0,2.0,1.0,34.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,2.0,3.0,normal,normal
2821,132118.0,12.0,2.0,2.0,78.0,2.0,2.0,2.0,6.0,2.0,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,abnormal,normal
661,141885.0,12.0,2.0,2.0,70.0,5.0,2.0,2.0,5.0,2.0,...,NaN,NaN,8.0,NaN,2.0,NaN,NaN,NaN,abnormal,normal
2211,134007.0,12.0,2.0,2.0,61.0,1.0,2.0,2.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,9.0,NaN,normal,high
1181,136701.0,12.0,2.0,1.0,31.0,1.0,2.0,1.0,NaN,3.0,...,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,abnormal,normal

In [36]:
#plineb, plinec
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import FunctionTransformer
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler



#Before imputing:

#drop SEQN, SDDSRVYR, RIDSTATR

#remove 7, 9: INQ300 INDFMMPC HIQ210 HIQ011 ALQ151 ALQ111 DMDEDUC2 DMQMILIZ




def singleremover(dat):
    if dat == 7 or dat == 9:
        return np.nan
    else:
        return dat
    
def singleremovermap(df):
    for column in df.columns:
        df[column] = df[column].map(singleremover)
    return df

srtransform = FunctionTransformer(singleremovermap)

srpipe = Pipeline([
    ("remove 7/9", srtransform),
    ("impute", SimpleImputer()),
    ("scale", MinMaxScaler())
])

srhotpipe = Pipeline([
    ("remove 7/9", srtransform),
    ("impute", SimpleImputer(strategy="most_frequent")),     #don't want to use mean if we're going to 1hot
    ("onehot", OneHotEncoder(min_frequency=0.01))

])

#remove 77, 99: DMDBORN4, IND310, HIQ032A, ALQ121, DMDMARTZ, DMDYRUSR

def doubleeremover(dat):
    if dat == 77 or dat == 99:
        return np.nan
    else:
        return dat
    
def doubleremovermap(df):
    for column in df.columns:
        df[column] = df[column].map(doubleeremover)
    return df

drtransform = FunctionTransformer(doubleremovermap)

drpipe = Pipeline([
    ("remove 77/99", drtransform),
    ("impute", SimpleImputer()),
    ("scale", MinMaxScaler())
])


drhotpipe = Pipeline([
    ("remove 77/99", drtransform),
    ("impute", SimpleImputer(strategy="most_frequent")),     #don't want to use mean if we're going to 1hot
    ("onehot", OneHotEncoder(min_frequency=0.01))
])


#remove 777, 999: ALQ130, ALQ170

def tripleeremover(dat):
    if dat == 77 or dat == 99:
        return np.nan
    else:
        return dat
    
def tripleremovermap(df):
    for column in df.columns:
        df[column] = df[column].map(tripleeremover)
    return df

trtransform = FunctionTransformer(tripleremovermap)

trpipe = Pipeline([
    ("remove 777/999", drtransform),
    ("impute", SimpleImputer()),
    ("scale", MinMaxScaler())
])

trhotpipe = Pipeline([
    ("remove 777/999", drtransform),
    ("impute", SimpleImputer(strategy="most_frequent")),     #don't want to use mean if we're going to 1hot
    ("onehot", OneHotEncoder(min_frequency=0.01))
])


hotpipe = Pipeline([
    ("impute", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(min_frequency=0.01))
])



#specail pipeline transform for ALQ121

def alc(dat):
    if dat == 77 or dat == 99:
        return np.nan
    if dat == 0:
        return 11       #to put the "never" value in its proper place
    else:
        return dat
    
def alcmap(df):
    for column in df.columns:
        df[column] = df[column].map(alc)
    return df

alctransform = FunctionTransformer(alcmap)

alcpipe = Pipeline([
    ("remove 777/999", alctransform),
    ("impute", SimpleImputer()),
    ("scale", MinMaxScaler())
])


def age(dat):
    if dat == 80:
        return 85
    else:
        return dat
    
def agemap(df):
    for column in df.columns:
        df[column] = df[column].map(age)
    return df

agetransform = FunctionTransformer(agemap)

agepipe = Pipeline([
    ("remove 777/999", agetransform),
    ("impute", SimpleImputer()),
    ("scale", MinMaxScaler())
])




imppipe = Pipeline([
    ("impute", SimpleImputer())         #can't remove the 7/9 values here because the values to be removed are different for different columns
])

In [37]:
plineb = ColumnTransformer([
    #drop seqn and SDDSRVYR, RIDSTATR


    ("remove 7/9", srpipe, ["INDFMMPC",  "HIQ011", "ALQ151", "ALQ111", "DMDEDUC2"]),
    ("remove 7/9 and 1hot", srhotpipe, ["DMQMILIZ", "HIQ210", "INQ300"]),
    
    ("remove 77/99", drpipe, ["IND310", "HIQ032A", "ALQ121",  "DMDYRUSR"]),
    ("remove 77/99 and 1hot", drhotpipe, ["DMDBORN4", "DMDMARTZ"]),
    
    ("remove 777/999", trpipe, ["ALQ130", "ALQ170"]),


    ("remove 77/99 and set 0 = 11", alcpipe, ["ALQ121"]),

    #impute all the rest. All transforms are done concurrently so had to impute the above ones seperatesly

    ("impute", imppipe, [ 
       'DMDHHSIZ',
        'ALQ151',
       'HIQ011',  
        #'HIQ032B', 'HIQ032D', 'HIQ032F', 'HIQ032H', 'HIQ032I',
        'INDFMMPC']),

    ("fix age bucket and impute", agepipe, [ 'RIDAGEYR']),
    
    ("onehot", hotpipe, ["RIAGENDR", "RIDRETH1"])



], remainder="drop")    #everything is at least going through the imputer. Would be faster to not imput when we know there are no NaNs!

In [38]:
plinec=plineb

In [39]:
#plineb.set_output(transform='pandas')

In [40]:
bp_training_Stanford.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BP,CHOL
3783,140293.0,12.0,2.0,2.0,63.0,1.0,2.0,1.0,NaN,3.0,...,NaN,NaN,NaN,NaN,1.0,3.0,2.0,3.0,abnormal,high
2412,136499.0,12.0,2.0,2.0,38.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,normal,normal
3834,141952.0,12.0,2.0,2.0,63.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,8.0,NaN,2.0,3.0,1.0,NaN,normal,borderline
2345,134955.0,12.0,2.0,1.0,65.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,normal,normal
3658,135090.0,12.0,2.0,2.0,70.0,5.0,2.0,2.0,6.0,5.0,...,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,abnormal,borderline

In [41]:
pd.DataFrame(plinec.fit_transform(chol_training_Stanford))

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,0.500000,0.0,0.000000,0.000000,0.75,0.0,1.0,0.0,1.0,0.0,...,1.0,2.000000,0.820896,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.681696,0.0,0.811895,0.102844,1.00,0.0,1.0,0.0,1.0,0.0,...,1.0,2.505978,0.701493,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.681696,0.0,1.000000,0.000000,0.75,0.0,1.0,0.0,1.0,0.0,...,1.0,2.505978,0.626866,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0.000000,0.0,1.000000,0.000000,0.75,0.0,1.0,0.0,1.0,0.0,...,1.0,1.000000,0.537313,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.500000,0.0,1.000000,0.000000,0.75,0.0,1.0,0.0,1.0,0.0,...,1.0,2.000000,0.716418,0.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4557,1.000000,0.0,1.000000,0.000000,1.00,0.0,1.0,0.0,1.0,0.0,...,1.0,3.000000,0.238806,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4558,0.681696,0.0,0.000000,0.102844,0.25,0.0,1.0,0.0,1.0,0.0,...,1.0,2.505978,0.895522,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4559,0.681696,0.0,0.811895,0.102844,0.25,0.0,1.0,0.0,1.0,0.0,...,1.0,2.505978,0.776119,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4560,0.000000,1.0,0.811895,1.000000,0.00,0.0,1.0,0.0,1.0,0.0,...,2.0,1.000000,0.641791,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4561,0.000000,0.0,0.811895,0.102844,0.50,0.0,1.0,0.0,1.0,0.0,...,1.0,1.000000,0.194030,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [42]:
pd.DataFrame(plineb.fit_transform(bp_training_Stanford))

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1.000000,0.0,0.000000,0.000000,0.5000,0.0,1.0,1.0,0.0,0.0,...,1.0,3.000000,0.671642,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,0.678799,0.0,0.812927,0.101704,1.0000,0.0,1.0,0.0,1.0,0.0,...,1.0,2.499641,0.298507,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,1.000000,0.0,1.000000,0.000000,0.7500,0.0,1.0,0.0,1.0,1.0,...,1.0,3.000000,0.671642,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,1.000000,0.0,1.000000,0.000000,1.0000,0.0,1.0,0.0,1.0,1.0,...,1.0,3.000000,0.701493,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.000000,0.0,0.812927,1.000000,1.0000,0.0,1.0,0.0,1.0,1.0,...,1.0,3.000000,0.776119,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4557,0.500000,0.0,1.000000,0.000000,0.2500,0.0,1.0,0.0,1.0,0.0,...,1.0,2.000000,0.492537,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4558,1.000000,0.0,1.000000,0.000000,0.7500,0.0,1.0,0.0,1.0,1.0,...,1.0,3.000000,0.104478,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4559,0.000000,0.0,0.812927,0.101704,0.7500,0.0,1.0,0.0,1.0,0.0,...,1.0,1.000000,0.119403,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4560,0.000000,0.0,1.000000,0.000000,0.7095,0.0,1.0,0.0,1.0,0.0,...,1.0,1.000000,0.014925,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4561,1.000000,0.0,1.000000,0.000000,1.0000,0.0,1.0,0.0,1.0,1.0,...,1.0,3.000000,0.283582,0.0,1.0,0.0,0.0,1.0,0.0,0.0

2
ensembles, an SVM, a Bayesian learner, and 2 other kinds of algorithms discussed in your textbook.

In [20]:
bp_training_Stanford["BP"]

3783    abnormal
2412      normal
3834      normal
2345      normal
3658    abnormal
          ...
2998    abnormal
900       normal
3108      normal
2876      normal
5582      normal
Name: BP, Length: 4562, dtype: str

In [21]:
bp_training_Stanford.drop(columns=["BP", "CHOL"])

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032A,HIQ032B,HIQ032D,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310
3783,140293.0,12.0,2.0,2.0,63.0,1.0,2.0,1.0,NaN,3.0,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,3.0,2.0,3.0
2412,136499.0,12.0,2.0,2.0,38.0,3.0,2.0,1.0,NaN,5.0,...,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
3834,141952.0,12.0,2.0,2.0,63.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,NaN,8.0,NaN,2.0,3.0,1.0,NaN
2345,134955.0,12.0,2.0,1.0,65.0,3.0,2.0,1.0,NaN,5.0,...,1.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN
3658,135090.0,12.0,2.0,2.0,70.0,5.0,2.0,2.0,6.0,5.0,...,NaN,2.0,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2998,130580.0,12.0,2.0,1.0,51.0,2.0,2.0,2.0,1.0,2.0,...,NaN,NaN,4.0,NaN,NaN,NaN,2.0,2.0,2.0,1.0
900,136079.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,6.0,NaN,NaN,2.0,3.0,1.0,NaN
3108,131930.0,12.0,2.0,2.0,26.0,1.0,2.0,2.0,6.0,4.0,...,NaN,NaN,NaN,NaN,8.0,NaN,2.0,1.0,2.0,1.0
2876,138262.0,12.0,2.0,1.0,19.0,1.0,2.0,1.0,NaN,NaN,...,NaN,NaN,4.0,NaN,NaN,NaN,2.0,1.0,2.0,1.0
5582,135484.0,12.0,2.0,2.0,37.0,3.0,2.0,1.0,NaN,5.0,...,1.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN

In [22]:
from sklearn.model_selection import cross_validate

def CV(model):
    print(list(model.named_steps.keys())[-1])
    bp =cross_validate(estimator=model, X=bp_training_Stanford.drop(columns=["BP", "CHOL"]), y=np.ravel(bp_training_Stanford[["BP"]]),  cv=10, scoring=["f1_macro", "recall_macro", "accuracy"])

    print("BP",
            bp)

    chol = cross_validate(estimator=model, X=chol_training_Stanford.drop(columns=["BP", "CHOL"]), y=np.ravel(bp_training_Stanford[["CHOL"]]),  cv=10, scoring=["f1_macro", "recall_macro", "accuracy"])
    
    print("CHOL",
        chol)
    return bp, chol

In [23]:
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier

from sklearn.linear_model import SGDClassifier

from sklearn.linear_model import RidgeClassifier

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from scipy.stats import uniform

Svc = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("SVC", SVC(random_state=42))
])


GnB = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("GaussianNB", GaussianNB())
])

DtStump = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("DecisionTreeStump", DecisionTreeClassifier(max_depth=1, random_state=42))
])

DtC = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("DecisionTreeClassifier", DecisionTreeClassifier(random_state=42))
])

DtCRSCV = RandomizedSearchCV(
    estimator=DtC,
    random_state=42,
    param_distributions=dict(DecisionTreeClassifier__min_impurity_decrease= uniform(0, 1), DecisionTreeClassifier__max_depth=randint(2, 10))
)




BgC = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("Bagging", BaggingClassifier(random_state=42))
])

AdaBC = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("AdaBoost", AdaBoostClassifier(random_state=42))
])

SgdC = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("SGDClassifier", SGDClassifier(random_state=42))
])



RidgeC = Pipeline([
    ("preprocces", plineb),             #assuming for simpliciy that we use the same pipeline for bp and chol
    ("RidgeClassifier", RidgeClassifier(random_state=42))
])

CVs seperated into cells because they're slow

In [46]:
DtCRSCV.fit(X=bp_training_Stanford.drop(columns=["BP", "CHOL"]), y=np.ravel(bp_training_Stanford[["BP"]]))

RandomizedSearchCV(estimator=Pipeline(steps=[('preprocces',
                                              ColumnTransformer(transformers=[('remove '
                                                                               '7/9',
                                                                               Pipeline(steps=[('remove '
                                                                                                '7/9',
                                                                                                FunctionTransformer(func=<function singleremovermap at 0x774a942f4900>)),
                                                                                               ('impute',
                                                                                                SimpleImputer()),
                                                                                               ('scale',
                                                                                                MinMaxScaler())]),
                                                                               ['INDFMMPC',
                                                                                'HIQ011',
                                                                                'ALQ151',
                                                                                'ALQ111',
                                                                                'DMDEDUC2']),
                                                                              ('remove '
                                                                               '7/9 '
                                                                               'and '
                                                                               '1hot',
                                                                               Pipeline(st...
                                                                                'RIDRETH1'])])),
                                             ('DecisionTreeClassifier',
                                              DecisionTreeClassifier(random_state=42))]),
                   param_distributions={'DecisionTreeClassifier__max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x774a3602b620>,
                                        'DecisionTreeClassifier__min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x774a3603af10>},
                   random_state=42)

In [ ]:
#DtC=DtCRSCV.best_estimator_

In [ ]:


svccvbp, svccvchol = CV(Svc)

SVC
BP {'fit_time': array([1.29534531, 0.87996864, 0.88547349, 1.40266967, 1.05831075,
       0.73863578, 0.82027531, 1.14787292, 0.93191075, 0.70404124]), 'score_time': array([0.14064908, 0.14806557, 0.14670587, 0.17160749, 0.11169624,
       0.2714746 , 0.14320922, 0.15941978, 0.12647796, 0.11560559]), 'test_f1_macro': array([0.62244187, 0.66675719, 0.62635696, 0.6375642 , 0.61163274,
       0.62379977, 0.6464346 , 0.63225806, 0.63126433, 0.65041543]), 'test_recall_macro': array([0.62396135, 0.66803865, 0.63015534, 0.64100971, 0.6198835 ,
       0.62470171, 0.64917642, 0.63314126, 0.63628427, 0.65636459]), 'test_accuracy': array([0.63676149, 0.68271335, 0.64692982, 0.65789474, 0.64035088,
       0.63596491, 0.66447368, 0.64473684, 0.65350877, 0.6754386 ])}
CHOL {'fit_time': array([1.72821856, 1.19213319, 1.09877515, 1.07081795, 1.12607574,
       1.09855771, 1.08013821, 1.00725198, 1.0110085 , 0.89449477]), 'score_time': array([0.11615157, 0.0923996 , 0.09979558, 0.09098101, 0.10011339,
       0.08872366, 0.14991426, 0.08576584, 0.08300424, 0.08051586]), 'test_f1_macro': array([0.24643678, 0.24643678, 0.24677716, 0.24677716, 0.24677716,
       0.2461964 , 0.24677716, 0.24677716, 0.24677716, 0.24677716]), 'test_recall_macro': array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]), 'test_accuracy': array([0.58643326, 0.58643326, 0.5877193 , 0.5877193 , 0.5877193 ,
       0.58552632, 0.5877193 , 0.5877193 , 0.5877193 , 0.5877193 ])}

In [25]:

GnBcvbp, GnBcvchol = CV(GnB)

GaussianNB
BP {'fit_time': array([0.08145857, 0.05356073, 0.0580101 , 0.05180478, 0.05614805,
       0.04844785, 0.04945493, 0.04748416, 0.04949737, 0.04849458]), 'score_time': array([0.02329993, 0.02167034, 0.02266502, 0.02060056, 0.02016926,
       0.0224545 , 0.02159119, 0.02059126, 0.02004743, 0.0197804 ]), 'test_f1_macro': array([0.56235629, 0.63083301, 0.56003976, 0.57442094, 0.58588392,
       0.61613761, 0.60327751, 0.61444619, 0.60776025, 0.6261763 ]), 'test_recall_macro': array([0.56237681, 0.63068599, 0.57765049, 0.57687379, 0.586     ,
       0.6200745 , 0.60342821, 0.61518538, 0.6078517 , 0.62595309]), 'test_accuracy': array([0.56892779, 0.6345733 , 0.56359649, 0.58991228, 0.59429825,
       0.61622807, 0.61184211, 0.61622807, 0.61622807, 0.63377193])}
CHOL {'fit_time': array([0.04782844, 0.04997444, 0.04678226, 0.0501008 , 0.05062366,
       0.05554342, 0.05783606, 0.08011055, 0.05775642, 0.05512524]), 'score_time': array([0.01989555, 0.01881289, 0.02118659, 0.01866412, 0.01953483,
       0.02616024, 0.0253756 , 0.03169274, 0.02378368, 0.02202535]), 'test_f1_macro': array([0.16664274, 0.31590608, 0.2991141 , 0.28912408, 0.15545689,
       0.31375082, 0.35247227, 0.32664156, 0.19390874, 0.31346107]), 'test_recall_macro': array([0.33922308, 0.33003166, 0.32054975, 0.31778071, 0.30887231,
       0.33042409, 0.35829295, 0.33249596, 0.33686903, 0.31980264]), 'test_accuracy': array([0.24507659, 0.49015317, 0.50438596, 0.50657895, 0.21929825,
       0.50438596, 0.51315789, 0.48464912, 0.26315789, 0.46052632])}

In [26]:


DtStumpcvbp, DtStumpcvchol = CV(DtStump)

DecisionTreeStump
BP {'fit_time': array([0.07903028, 0.05836391, 0.06930828, 0.0612042 , 0.05951571,
       0.05848598, 0.05479908, 0.05179024, 0.05165935, 0.0557518 ]), 'score_time': array([0.02398276, 0.02811813, 0.03443265, 0.02221251, 0.02254033,
       0.02611351, 0.02195334, 0.02097845, 0.02043247, 0.02191186]), 'test_f1_macro': array([0.61833526, 0.66057635, 0.65591988, 0.6159461 , 0.62768553,
       0.63222233, 0.61278212, 0.63902851, 0.63160668, 0.64221081]), 'test_recall_macro': array([0.61811594, 0.6605314 , 0.65526214, 0.61786408, 0.62741748,
       0.63203539, 0.61384669, 0.63887434, 0.63351959, 0.6459461 ]), 'test_accuracy': array([0.62582057, 0.67177243, 0.6622807 , 0.63157895, 0.63596491,
       0.63596491, 0.625     , 0.64254386, 0.64692982, 0.6622807 ])}
CHOL {'fit_time': array([0.05936766, 0.05198908, 0.06389952, 0.05527782, 0.05610466,
       0.06861305, 0.05475783, 0.05364823, 0.05335569, 0.0511477 ]), 'score_time': array([0.02085257, 0.02211452, 0.0222137 , 0.01987553, 0.02389956,
       0.02517819, 0.02125382, 0.02033257, 0.0214932 , 0.01950431]), 'test_f1_macro': array([0.24643678, 0.24643678, 0.24677716, 0.24677716, 0.24677716,
       0.2461964 , 0.24677716, 0.24677716, 0.24677716, 0.24677716]), 'test_recall_macro': array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]), 'test_accuracy': array([0.58643326, 0.58643326, 0.5877193 , 0.5877193 , 0.5877193 ,
       0.58552632, 0.5877193 , 0.5877193 , 0.5877193 , 0.5877193 ])}

In [51]:
DtCcvbp, DtCcvchol = CV(DtC)

DecisionTreeClassifier
BP {'fit_time': array([0.1119957 , 0.08786798, 0.08327818, 0.06809282, 0.08649492,
       0.09247041, 0.06171679, 0.06557822, 0.06263638, 0.0709815 ]), 'score_time': array([0.02454019, 0.03593373, 0.01952124, 0.0296061 , 0.02363467,
       0.02289748, 0.02227235, 0.02175164, 0.01944232, 0.02017617]), 'test_f1_macro': array([0.53722074, 0.58671977, 0.54160223, 0.51501377, 0.53312921,
       0.5700431 , 0.59602017, 0.56747967, 0.58384316, 0.58894231]), 'test_recall_macro': array([0.5385314 , 0.58743961, 0.54213592, 0.51500971, 0.53314563,
       0.57342413, 0.59583261, 0.56772016, 0.58462837, 0.58902276]), 'test_accuracy': array([0.53829322, 0.58862144, 0.54385965, 0.51973684, 0.5372807 ,
       0.57017544, 0.60087719, 0.57017544, 0.58552632, 0.59210526])}
CHOL {'fit_time': array([0.07156348, 0.06821728, 0.07677174, 0.06957269, 0.06758237,
       0.06956339, 0.06870341, 0.07047963, 0.07344151, 0.07055163]), 'score_time': array([0.02166462, 0.02127862, 0.02260327, 0.02026486, 0.01879382,
       0.01916051, 0.01998377, 0.0235014 , 0.02534533, 0.02184415]), 'test_f1_macro': array([0.363695  , 0.31626189, 0.3325263 , 0.31946843, 0.31276068,
       0.34218301, 0.3157807 , 0.33901399, 0.33579683, 0.32412733]), 'test_recall_macro': array([0.36409116, 0.31665662, 0.33329272, 0.32005167, 0.31173046,
       0.34244316, 0.31522687, 0.34018634, 0.33749621, 0.32332337]), 'test_accuracy': array([0.45076586, 0.39387309, 0.41447368, 0.4122807 , 0.41008772,
       0.42105263, 0.39912281, 0.41666667, 0.42982456, 0.41447368])}

In [28]:

BgCcvbp, BgCcvchol = CV(BgC)

Bagging
BP {'fit_time': array([0.23147893, 0.23398662, 0.2498951 , 0.25453901, 0.26826763,
       0.31788182, 0.246454  , 0.22630715, 0.21444249, 0.24660492]), 'score_time': array([0.02749157, 0.03500628, 0.04025006, 0.03195596, 0.04042268,
       0.04991913, 0.02834821, 0.0296104 , 0.02701354, 0.02790165]), 'test_f1_macro': array([0.60561243, 0.604329  , 0.59980054, 0.58167614, 0.56125123,
       0.58871337, 0.58946913, 0.60531401, 0.58964562, 0.5717711 ]), 'test_recall_macro': array([0.60713043, 0.60554589, 0.60143689, 0.58229126, 0.56932039,
       0.58934288, 0.59132181, 0.60857924, 0.59330074, 0.57482102]), 'test_accuracy': array([0.61925602, 0.61706783, 0.61403509, 0.59210526, 0.5877193 ,
       0.59868421, 0.60307018, 0.62280702, 0.60745614, 0.5877193 ])}
CHOL {'fit_time': array([0.2620573 , 0.26310015, 0.39755845, 0.27157879, 0.21826029,
       0.20321369, 0.19604802, 0.2128408 , 0.19930053, 0.19239831]), 'score_time': array([0.029073  , 0.05027056, 0.03611946, 0.02685046, 0.02278352,
       0.02323341, 0.02212429, 0.02024746, 0.02623796, 0.02119851]), 'test_f1_macro': array([0.32034793, 0.33616576, 0.32358887, 0.33151218, 0.26900188,
       0.30155112, 0.29779168, 0.32218752, 0.29466784, 0.30231184]), 'test_recall_macro': array([0.3287326 , 0.33921805, 0.32962568, 0.33833892, 0.28074875,
       0.30784247, 0.30806556, 0.32765762, 0.30928139, 0.30995714]), 'test_accuracy': array([0.47921225, 0.47702407, 0.47587719, 0.48903509, 0.43421053,
       0.44298246, 0.45614035, 0.46929825, 0.46710526, 0.45614035])}

In [ ]:


AdaBCcvbp, AdaBCcvchol = CV(AdaBC)

AdaBoost
BP {'fit_time': array([0.33284998, 0.29232597, 0.32403803, 0.28254414, 0.29950237,
       0.29188848, 0.3204186 , 0.30917692, 0.31059194, 0.28471756]), 'score_time': array([0.02850795, 0.02426767, 0.02433968, 0.02776241, 0.02478004,
       0.02932167, 0.02789497, 0.02690291, 0.02861238, 0.02280545]), 'test_f1_macro': array([0.62131219, 0.67067019, 0.66962222, 0.61373858, 0.61401417,
       0.62864992, 0.61993741, 0.65226913, 0.63479023, 0.64829288]), 'test_recall_macro': array([0.62128502, 0.67128502, 0.66883495, 0.61658252, 0.61586408,
       0.62836855, 0.62147139, 0.65170828, 0.63712822, 0.65316338]), 'test_accuracy': array([0.63019694, 0.68490153, 0.67763158, 0.63157895, 0.62938596,
       0.63596491, 0.63377193, 0.65789474, 0.65131579, 0.67105263])}
CHOL {'fit_time': array([0.33227658, 0.31705546, 0.3107245 , 0.30806375, 0.3076725 ,
       0.30531478, 0.32143378, 0.31241536, 0.31335711, 0.31563544]), 'score_time': array([0.02478814, 0.0231359 , 0.02314401, 0.02223945, 0.02325845,
       0.02387309, 0.02487946, 0.02282953, 0.0239377 , 0.02214885]), 'test_f1_macro': array([0.24643678, 0.24643678, 0.24677716, 0.24677716, 0.24677716,
       0.2461964 , 0.24677716, 0.24677716, 0.24677716, 0.24677716]), 'test_recall_macro': array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]), 'test_accuracy': array([0.58643326, 0.58643326, 0.5877193 , 0.5877193 , 0.5877193 ,
       0.58552632, 0.5877193 , 0.5877193 , 0.5877193 , 0.5877193 ])}

In [30]:



SgdCcvbp, SgdCcvchol = CV(SgdC)

SGDClassifier
BP {'fit_time': array([0.08853197, 0.07918692, 0.10341692, 0.08966231, 0.09059691,
       0.0710578 , 0.06905222, 0.0778079 , 0.08645535, 0.07099938]), 'score_time': array([0.02265358, 0.0213294 , 0.01835299, 0.019768  , 0.01960135,
       0.01955247, 0.01982546, 0.0214982 , 0.01980829, 0.0201447 ]), 'test_f1_macro': array([0.60378417, 0.53433212, 0.59869218, 0.62907982, 0.63406768,
       0.59458659, 0.59766064, 0.45714286, 0.51434794, 0.59857295]), 'test_recall_macro': array([0.61014493, 0.58436715, 0.61361165, 0.63258252, 0.63629126,
       0.59536698, 0.59912112, 0.53989873, 0.57371515, 0.60651301]), 'test_accuracy': array([0.62800875, 0.55798687, 0.63815789, 0.64912281, 0.65131579,
       0.60526316, 0.59868421, 0.57894737, 0.60964912, 0.625     ])}
CHOL {'fit_time': array([0.16387773, 0.16340065, 0.1769712 , 0.16855693, 0.15097904,
       0.17879701, 0.18744874, 0.16419315, 0.16439891, 0.16227603]), 'score_time': array([0.02259755, 0.01835203, 0.01790547, 0.021348  , 0.01970363,
       0.02251029, 0.02125883, 0.0182991 , 0.01886678, 0.01938796]), 'test_f1_macro': array([0.22312335, 0.34158093, 0.24677716, 0.29566552, 0.24677716,
       0.2461964 , 0.12105061, 0.27974037, 0.24561404, 0.24677716]), 'test_recall_macro': array([0.30632444, 0.34162772, 0.33333333, 0.31120757, 0.33333333,
       0.33333333, 0.33121011, 0.34419958, 0.33084577, 0.33333333]), 'test_accuracy': array([0.27133479, 0.41794311, 0.5877193 , 0.38815789, 0.5877193 ,
       0.58552632, 0.21710526, 0.29605263, 0.58333333, 0.5877193 ])}

In [31]:



RidgeCcvbp, RidgeCcvchol = CV(RidgeC)

RidgeClassifier
BP {'fit_time': array([0.08179355, 0.05579615, 0.06730843, 0.05581403, 0.05184889,
       0.05194926, 0.07062364, 0.07115149, 0.05572057, 0.05264807]), 'score_time': array([0.02144003, 0.01971102, 0.01962709, 0.01931453, 0.02041721,
       0.02299166, 0.02730536, 0.02075887, 0.02025986, 0.02078724]), 'test_f1_macro': array([0.61406523, 0.66962765, 0.64504822, 0.61850827, 0.62382821,
       0.63523559, 0.63815767, 0.66499136, 0.63099425, 0.64568765]), 'test_recall_macro': array([0.61377778, 0.66936232, 0.64499029, 0.61885437, 0.62514563,
       0.63482917, 0.63800128, 0.66460043, 0.63232641, 0.64876899]), 'test_accuracy': array([0.61925602, 0.68052516, 0.65570175, 0.62938596, 0.63815789,
       0.64035088, 0.64692982, 0.66885965, 0.64473684, 0.66447368])}
CHOL {'fit_time': array([0.05356288, 0.05274153, 0.05348206, 0.05490232, 0.05273938,
       0.05314922, 0.05158591, 0.0515461 , 0.05051661, 0.0594511 ]), 'score_time': array([0.01978469, 0.01926661, 0.02561092, 0.02034664, 0.01894808,
       0.02151084, 0.02027059, 0.01863599, 0.02412152, 0.02359748]), 'test_f1_macro': array([0.24643678, 0.24643678, 0.2461964 , 0.24677716, 0.24677716,
       0.2461964 , 0.24677716, 0.24677716, 0.2461964 , 0.24677716]), 'test_recall_macro': array([0.33333333, 0.33333333, 0.33208955, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33208955, 0.33333333]), 'test_accuracy': array([0.58643326, 0.58643326, 0.58552632, 0.5877193 , 0.5877193 ,
       0.58552632, 0.5877193 , 0.5877193 , 0.58552632, 0.5877193 ])}

In [36]:
np.set_printoptions(suppress=True)  #get rid of scientific notation to make our Anova outputs readbale

In [37]:
from scipy.stats import f_oneway

databp = np.array([data["test_f1_macro"] for data in [RidgeCcvbp, SgdCcvbp, AdaBCcvbp, BgCcvbp, DtCcvbp, DtStumpcvbp, GnBcvbp, svccvbp]])

#sanity check
#databp[2] = [9999999999999999999999, 9999999999999999999999 ,9999999999999999999999 ,9999999999999999999999 ,9999999999999999999999 ,9999999999999999999999 , 9999999999999999999999, 9999999999999999999999, 9999999999999999999999,9999999999999999999999 ]
f_oneway(databp, axis=1)

F_onewayResult(statistic=np.float64(12.45508375564056), pvalue=np.float64(2.4359797438749007e-10))

In [38]:
datachol = np.array([data["test_f1_macro"] for data in [RidgeCcvchol, SgdCcvchol, AdaBCcvchol, BgCcvchol, DtCcvchol, DtStumpcvchol, GnBcvchol, svccvchol]])

f_oneway(datachol, axis=1)

F_onewayResult(statistic=np.float64(9.871086667672133), pvalue=np.float64(1.4368376018684538e-08))

In [39]:
from scipy.stats import f_oneway

databp = np.array([data["test_accuracy"] for data in [RidgeCcvbp, SgdCcvbp, AdaBCcvbp, BgCcvbp, DtCcvbp, DtStumpcvbp, GnBcvbp, svccvbp]])

f_oneway(databp, axis=1)

F_onewayResult(statistic=np.float64(20.836347306545534), pvalue=np.float64(4.891433130449153e-15))

In [105]:
df = pd.DataFrame(databp).transpose()
#df.insert(0, "", ["RidgeCcvbp", "SgdCcvbp", "AdaBCcvbp", "BgCcvbp", "DtCcvbp", "DtStumpcvbp", "GnBcvbp", "svccvbp"])
df.columns=["RidgeC", "SgdC", "AdaBC", "BgC", "DtC", "DtStump", "GnB", "svc"]
df.describe()

,RidgeC,SgdC,AdaBC,BgC,DtC,DtStump,GnB,svc
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.648838,0.614214,0.650369,0.604992,0.564665,0.644014,0.604561,0.653877
std,0.018728,0.030226,0.021355,0.013169,0.027950,0.016416,0.024683,0.016171
min,0.619256,0.557987,0.629386,0.587719,0.519737,0.625000,0.563596,0.635965
25%,0.638706,0.600329,0.632127,0.593750,0.539685,0.632675,0.591009,0.641447
50%,0.645833,0.617325,0.643640,0.605263,0.570175,0.639254,0.614035,0.650219
75%,0.662281,0.635621,0.667763,0.616310,0.587848,0.658443,0.616228,0.662829
max,0.680525,0.651316,0.684902,0.622807,0.600877,0.671772,0.634573,0.682713

In [106]:
df2 = pd.DataFrame(datachol).transpose()
#df.insert(0, "", ["RidgeCcvbp", "SgdCcvbp", "AdaBCcvbp", "BgCcvbp", "DtCcvbp", "DtStumpcvbp", "GnBcvbp", "svccvbp"])
df2.columns=["RidgeC", "SgdC", "AdaBC", "BgC", "DtC", "DtStump", "GnB", "svc"]
df2.describe()

,RidgeC,SgdC,AdaBC,BgC,DtC,DtStump,GnB,svc
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.246535,0.249330,0.246651,0.309913,0.330161,0.246651,0.272648,0.246651
std,0.000270,0.056537,0.000213,0.020502,0.015770,0.000213,0.072000,0.000213
min,0.246196,0.121051,0.246196,0.269002,0.312761,0.246196,0.155457,0.246196
25%,0.246256,0.245760,0.246522,0.298732,0.317064,0.246522,0.217713,0.246522
50%,0.246607,0.246777,0.246777,0.311330,0.328327,0.246777,0.306288,0.246777
75%,0.246777,0.271500,0.246777,0.323239,0.338210,0.246777,0.315367,0.246777
max,0.246777,0.341581,0.246777,0.336166,0.363695,0.246777,0.352472,0.246777

In [104]:
df.describe()/df2.describe()

,RidgeCcvbp,SgdCcvbp,AdaBCcvbp,BgCcvbp,DtCcvbp,DtStumpcvbp,GnBcvbp,svccvbp
count,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
mean,2.631830,2.463454,2.636800,1.952137,1.710270,2.611032,2.217368,2.651022
std,69.343453,0.534625,100.069710,0.642310,1.772346,76.924387,0.342814,75.778331
min,2.515293,4.609534,2.556438,2.184815,1.661772,2.538624,3.625420,2.583161
25%,2.593662,2.442748,2.564183,1.987570,1.702135,2.566407,2.714629,2.601990
50%,2.618877,2.501547,2.608184,1.944122,1.736609,2.590411,2.004766,2.634844
75%,2.683720,2.341148,2.705936,1.906671,1.738116,2.668168,1.954001,2.685941
max,2.757650,1.906769,2.775385,1.852678,1.652146,2.722182,1.800350,2.766518

In [69]:
from sklearn.metrics import f1_score
SgdC.fit(X=bp_training_Stanford.drop(columns=["BP", "CHOL"]), y=np.ravel(bp_training_Stanford[["BP"]]))

f1_score(SgdC.predict(bp_test_Stanford.drop(columns=["BP", "CHOL"])), np.ravel(bp_test_Stanford[["BP"]]), average="macro")

0.6162300500471642

In [ ]:
from sklearn.metrics import f1_score
SgdC.fit(X=bp_training_Stanford.drop(columns=["BP", "CHOL"]), y=np.ravel(bp_training_Stanford[["BP"]]))

f1_score(SgdC.predict(bp_test_Stanford.drop(columns=["BP", "CHOL"])), np.ravel(bp_test_Stanford[["BP"]]), average="macro")

a decision stump, a larger decision tree, 2
ensembles, an SVM, a Bayesian learner, and 2 other kinds of algorithms discussed in your textbook.

In [61]:
import cloudpickle
#  Svc
SgdC.fit( X=bp_training_Stanford.drop(columns=["BP", "CHOL"]), y=np.ravel(bp_training_Stanford[["CHOL"]]))

# Dump your fitted model into `model.joblib` within the current directory
with open('model.pkl', 'wb') as f:
    cloudpickle.dump(SgdC, f)
from huggingface_hub import HfApi, login, create_repo

# Ensure you use a token that has 'write' access
login()
api = HfApi()
from submit import upload_files

repo_id = "Project"
upload_files(api, repo_id, display)

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/nstanford14/Project/commit/b6e3ae00a7b4930539e19039ff33d8f3136e36b1', commit_message='Upload model.pkl with huggingface_hub', commit_description='', oid='b6e3ae00a7b4930539e19039ff33d8f3136e36b1', pr_url=None, repo_url=RepoUrl('https://huggingface.co/nstanford14/Project', endpoint='https://huggingface.co', repo_type='model', repo_id='nstanford14/Project'), pr_revision=None, pr_num=None)

No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/nstanford14/Project/commit/b6e3ae00a7b4930539e19039ff33d8f3136e36b1', commit_message='Upload pyproject.toml with huggingface_hub', commit_description='', oid='b6e3ae00a7b4930539e19039ff33d8f3136e36b1', pr_url=None, repo_url=RepoUrl('https://huggingface.co/nstanford14/Project', endpoint='https://huggingface.co', repo_type='model', repo_id='nstanford14/Project'), pr_revision=None, pr_num=None)

No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/nstanford14/Project/commit/b6e3ae00a7b4930539e19039ff33d8f3136e36b1', commit_message='Upload .python-version with huggingface_hub', commit_description='', oid='b6e3ae00a7b4930539e19039ff33d8f3136e36b1', pr_url=None, repo_url=RepoUrl('https://huggingface.co/nstanford14/Project', endpoint='https://huggingface.co', repo_type='model', repo_id='nstanford14/Project'), pr_revision=None, pr_num=None)

{'repo_id': 'nstanford14/Project'}

import cloudpickle
#SgdC  Svc
AdaBC.fit( X=bp_training_Stanford.drop(columns=["BP", "CHOL"]), y=np.ravel(bp_training_Stanford[["BP"]]))

# Dump your fitted model into `model.joblib` within the current directory
with open('model.pkl', 'wb') as f:
    cloudpickle.dump(AdaBC, f)
from huggingface_hub import HfApi, login, create_repo

# Ensure you use a token that has 'write' access
login()
api = HfApi()
from submit import upload_files

repo_id = "Project"
upload_files(api, repo_id, display)